CREATE TABLE IF NOT EXISTS `applications` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `application_code` VARCHAR(32) NOT NULL,
  `name` VARCHAR(80) NOT NULL,
  `phone` VARCHAR(30) NOT NULL,
  `wechat` VARCHAR(80) DEFAULT NULL,
  `city` VARCHAR(100) NOT NULL,
  `identity` VARCHAR(100) NOT NULL,
  `direction` VARCHAR(100) NOT NULL,
  `experience` TEXT DEFAULT NULL,
  `introduction` TEXT NOT NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'pending',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_application_code` (`application_code`),
  KEY `idx_created_at` (`created_at`),
  KEY `idx_status` (`status`),
  KEY `idx_phone` (`phone`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
